package com.iseecam.message.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "iseecam_message")
public class MessageEntity {

    @DynamoDBRangeKey
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "room-index")
    private String room;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private long updateTime;

    @DynamoDBAttribute
    private long creationTime;

    @DynamoDBAttribute
    private String message;

    @DynamoDBAttribute
    private String type;

    @DynamoDBAttribute
    private String sender;

    @DynamoDBAttribute
    private boolean read;

}
