spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_I6C1Be6u7
dynamo:
  accessKey: AKIA4B7GKBMAY6MVVA3U
  secretKey: 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
sqs:
  accessKey: AKIA4B7GKBMA3Y3ZPHJY
  secretKey: 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
  endpoint: https://sqs.eu-west-1.amazonaws.com/828874820353/roulette-queue.fifo
aws:
  apigateway: 
    endpoint: glhiy7ub83.execute-api.eu-west-1.amazonaws.com
    stage: prod
    region: eu-west-1
    secretKey: OlGmz4viIviGq761G6wBbGi41akbm9m36wAwXqY0
    accessKey: AKIA4B7GKBMAUOUQTE2Z