spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_2B7xVU4hZ
dynamo:
  accessKey: AKIA4B7GKBMAY6MVVA3U
  secretKey: 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
aws:
  apigateway: 
    endpoint: z2a5fqdqob.execute-api.eu-west-1.amazonaws.com
    stage: prod
    region: eu-west-1